name: Deploy Helpdesk to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Self-hHsted Runner
    runs-on: self-hosted


    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Go to Directory
        run: cd /var/www/brukerGuide

      - name: Pull Latest Changes
        run: git pull --no-edit origin main

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
            node-version: "22"

      - name: Install Dependencies
        working-directory: ./
        run: npm install

      - name: Reload With PM2
        run: |
              echo "Reloading Server"
              pm2 reload server --update-env

      - name: Verify PM2 Status
        run: |
              pm2 status
              if pm2 list | grap -qE "errored|stopped"; then
                echo "One or more processes have errored or stopped"
                exit 1
              fi

          